# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigerline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='state_fips_code',
            field=models.CharField(max_length=2, verbose_name=b'State FIPS Code'),
        ),
    ]
